name: unit Test

on:
  workflow_dispatch:
  push:

jobs:
  unit-test:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Install python
        uses: actions/setup-python@v3

      - name: Install python dependencies from requirments.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

       - name: Run Tests
         run: |
           echo "Changing to DAG Directory"
           cd DAGS
           echo "Listing the files under DAGS folder"
           echo ""
           ls
           python unit_test.py 2>&1import datetime
